"""toc

Revision ID: 12e64a32d52b
Revises: 156e5a4d9be2
Create Date: 2013-02-01 20:00:39.024558

"""

# revision identifiers, used by Alembic.
revision = '12e64a32d52b'
down_revision = '156e5a4d9be2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('toc', sa.Text(), nullable=True))
    op.add_column('version', sa.Column('toc', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('version', 'toc')
    op.drop_column('page', 'toc')
    ### end Alembic commands ###
