"""basic tables

Revision ID: 156e5a4d9be2
Revises: None
Create Date: 2013-02-01 19:52:12.861214

"""

# revision identifiers, used by Alembic.
revision = '156e5a4d9be2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('source', 'target')
    )
    op.create_table('page',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('title')
    )
    op.create_table('version',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page'], ['page.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version')
    op.drop_table('page')
    op.drop_table('link')
    ### end Alembic commands ###
